name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DotNetOpenAPI

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore DotNetOpenAPI/DotNetOpenAPI.csproj

    name: Build and Generate Swagger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Start ASP.NET Core application
      env:
        ASPNETCORE_URLS: http://localhost:5001
      run: |
        nohup dotnet ./publish/DotNetOpenAPI.dll &
        sleep 10
        # Check if the application is running
        curl -f http://localhost:5001/swagger/v1/swagger.json || exit 1

    - name: Download swagger.json
      run: curl http://localhost:5001/swagger/v1/swagger.json -o swagger.json

    - name: Upload swagger.json
      uses: actions/upload-artifact@v2
      with:
        name: swagger-json
        path: swagger.json
   
    - name: Upload OpenAPI Documentation as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: swagger-json
        path: swagger.json
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
        include-hidden-files: true

    - name: Test
      run: dotnet test --no-build --verbosity normal DotNetOpenAPI/DotNetOpenAPI.csproj
