name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore https://github.com/kaushiknatua12345/EnginneringDocRepo/tree/master/DotNetOpenAPI/DotNetOpenAPI

    - name: Build
      run: dotnet build --configuration Release DotNetOpenAPI/DotNetOpenAPI.csproj

    - name: Install Swagger tool locally
      run: |
        cd DotNetOpenAPI
        dotnet new tool-manifest
        dotnet tool install Swashbuckle.AspNetCore.Cli --version 7.2.0

    - name: Generate OpenAPI Documentation
      run: |
        cd DotNetOpenAPI
        dotnet tool restore  # Restores any dotnet tools (if needed)
        dotnet publish --configuration Release  # Publish the application
        dotnet tool run swagger tofile --output ./swagger.json bin/Release/net8.0/DotNetOpenAPI.dll v1  # Generate the OpenAPI documentation
      env:
        DOTNET_ROLL_FORWARD: LatestMajor

    - name: Verify Swagger JSON
      run: |
        cd DotNetOpenAPI
        if [ ! -f ./swagger.json ]; then
          echo "Swagger JSON file not found!"
          exit 1
        fi
        ls -la ./swagger.json

    - name: Upload OpenAPI Documentation as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openapi-docs
        path: DotNetOpenAPI/swagger.json  # Path to your generated OpenAPI specification (e.g., swagger.json)
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
        include-hidden-files: true

    - name: Test
      run: dotnet test --no-build --verbosity normal DotNetOpenAPI/DotNetOpenAPI.csproj
