name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DotNetOpenAPI

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore DotNetOpenAPI/DotNetOpenAPI.csproj

    - name: Build
      run: dotnet build --configuration Release DotNetOpenAPI/DotNetOpenAPI.csproj     
   
    - name: Upload OpenAPI Documentation as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openapi-docs
        path: DotNetOpenAPI/swagger.json  # Path to your generated OpenAPI specification (e.g., swagger.json)
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
        include-hidden-files: true

    - name: Test
      run: dotnet test --no-build --verbosity normal DotNetOpenAPI/DotNetOpenAPI.csproj
