name: Build and Generate Swagger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Install Swagger tool
      run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 7.2.0

    - name: Generate Swagger JSON
      run: dotnet swagger tofile --output ./swagger.json DotNetOpenAPI/DotNetOpenAPI/bin/Release/net8.0/DotNetOpenAPI.dll v1
      env:
        DOTNET_ROLL_FORWARD: LatestMajor

    - name: Upload Swagger JSON
      uses: actions/upload-artifact@v2
      with:
        name: swagger-json
        path: ./swagger.json
