name: Generate OpenAPI Manifest

on:
  push:
    branches: none # [ master ]
  pull_request:
    branches: none # [ master ]    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: DotNetOpenAPI

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    # Step 7: Upload OpenAPI documentation (swagger.json) as an artifact
    - name: Upload OpenAPI Documentation
      run: |
          curl -s https://raw.githubusercontent.com/${{ github.EngineeringDocRepo }}/master/swagger/v1/swagger.json -o swagger.json
      continue-on-error: true

    - name: Upload OpenAPI documentation as artifact
      uses: actions/upload-artifact@v3
      with:
          name: swagger-doc
          path: ./swagger.json
