name: Upload OpenAPI Specification

on:
  push:
    branches:
      - main  # This will trigger on push to the main branch
  pull_request:
    branches:
      - main  # Also trigger on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Replace with your .NET version

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build API project
        run: |
          dotnet build

      - name: Generate OpenAPI specification
        run: |
          # Run the API locally to generate the OpenAPI JSON file
          dotnet run --project C:/Users/knatua/Videos/OpenAPIWith.NET/DotNetOpenAPI/DotNetOpenAPI/DotNetOpenAPI.csproj &

          # Allow some time for the API to start
          sleep 10

          # Fetch the OpenAPI spec (swagger.json) from the local server
          curl -o openapi.json http://localhost:5108/swagger/v1/swagger.json

      - name: Commit and push OpenAPI to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'openapi.json'
          message: 'Update OpenAPI documentation'
          author_name: 'Kaushik Natua'
          author_email: 'kaushik.natua@hyland.com'
          push: true
