name: Build and Generate Swagger

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DotNetOpenAPI

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Generate OpenAPI Documentation
      run: |
          dotnet tool restore  # Restores any dotnet tools (if needed)
          dotnet publish --configuration Release --output swagger.json  # Publish the application
          # If using Swashbuckle, the OpenAPI specification is generated here
          echo "OpenAPI documentation generated"

    - name: Upload OpenAPI Documentation as Artifact
      uses: actions/upload-artifact@v4
      with:
          name: openapi-docs
          path: ./swagger.json  # Path to your generated OpenAPI specification (e.g., swagger.json)
          if-no-files-found: warn
          compression-level: 6
          overwrite: true
          include-hidden-files: true
      env:
        DOTNET_ROOT: /home/runner/.dotnet

