name: Generate OpenAPI Manifest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

    steps:
     - uses: actions/checkout@v2

     - name: Setup .NET Core
    
       uses: actions/setup-dotnet@v1
       with:
       dotnet-version: 3.1.x

     - name: Install dependencies
       run: dotnet restore

     - name: Build
       run: dotnet build --configuration Release

    # Generate OpenAPI documentation
    - name: Generate OpenAPI manifest
      run: |
        # Run the .NET Core project to generate the Swagger JSON (OpenAPI Manifest)
        dotnet publish --configuration Release --output ./publish
        curl -o swagger.json http://localhost:5000/swagger/v1/swagger.json  # Replace with your actual URL if necessary
        
    # Upload the generated OpenAPI manifest as an artifact
    - name: Upload OpenAPI Manifest as artifact
      uses: actions/upload-artifact@v3
      with:
        name: swagger-json
        path: swagger.json
