name: Generate OpenAPI Manifest

on:
  push:
    branches: none # [ master ]
  pull_request:
    branches: none # [ master ]    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  build-dotnet-app:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: DotNetOpenAPI

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    # Generate OpenAPI documentation
    - name: Generate OpenAPI manifest
      run: |
        # Run the .NET Core project to generate the Swagger JSON (OpenAPI Manifest)
        dotnet publish --configuration Release --output ./publish
        curl -o swagger.json http://localhost:5000/swagger/v1/swagger.json  # Replace with your actual URL if necessary
        
    # Upload the generated OpenAPI manifest as an artifact
    - name: Upload OpenAPI Manifest as artifact
      uses: actions/upload-artifact@v3
      with:
        name: swagger-json
        path: swagger.json
