name: Build and Generate Swagger

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: DotNetOpenAPI

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Install Swagger tool locally
      run: dotnet new tool-manifest && dotnet tool install Swashbuckle.AspNetCore.Cli --version 7.2.0

    - name: Generate Swagger JSON
      run: dotnet tool run swagger tofile --output ./swagger.json DotNetOpenAPI/DotNetOpenAPI/bin/Release/net8.0/DotNetOpenAPI.dll v1
      env:
        DOTNET_ROLL_FORWARD: LatestMajor

    - name: Upload Swagger JSON
      uses: actions/upload-artifact@v4
      with:
        name: swagger-json
        path: ./swagger.json
