name: Download OpenAPI Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DotNetOpenAPI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # You can change this to the version you're using

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Generate OpenAPI documentation
      run: dotnet tool swagger tofile --output ./swagger.json DotNetOpenAPI/DotNetOpenAPI/bin/Release/net8.0/DotNetOpenAPI.dll v1 
      # Adjust the paths and version accordingly.

    - name: Upload OpenAPI JSON as artifact
      uses: actions/upload-artifact@v4
      with:
        name: openapi-docs
        path: ./swagger.json
