name: Generate and Upload OpenAPI Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DotNetOpenAPI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Adjust based on your project's .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./published

      - name: Run API to generate OpenAPI (Swagger) file
        run: |
          dotnet ./published/DotNetOpenAPI.dll &
          sleep 10  # Wait for the app to start and be ready
          curl -o swagger.json http://127.0.0.1:5108/swagger/v1/swagger.json

      - name: Upload OpenAPI JSON as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: swagger-docs
          path: swagger.json
